// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsBunny.Tests")>]
[<assembly: AssemblyProductAttribute("FsBunny")>]
[<assembly: AssemblyDescriptionAttribute("Streaming F# API for RabbitMQ")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsBunny.Tests"
    let [<Literal>] AssemblyProduct = "FsBunny"
    let [<Literal>] AssemblyDescription = "Streaming F# API for RabbitMQ"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
